// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/psksketch/v1/psksketch.proto

package psksketchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRequest) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *InsertRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InsertRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeries    []*TimeSeries          `protobuf:"bytes,1,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertRequest) Reset() {
	*x = BatchInsertRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertRequest) ProtoMessage() {}

func (x *BatchInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertRequest.ProtoReflect.Descriptor instead.
func (*BatchInsertRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{3}
}

func (x *BatchInsertRequest) GetTimeSeries() []*TimeSeries {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

type TimeSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Samples       []*Sample              `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeries) Reset() {
	*x = TimeSeries{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeries) ProtoMessage() {}

func (x *TimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeries.ProtoReflect.Descriptor instead.
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeries) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TimeSeries) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type BatchInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int64                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Failed        int64                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertResponse) Reset() {
	*x = BatchInsertResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertResponse) ProtoMessage() {}

func (x *BatchInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertResponse.ProtoReflect.Descriptor instead.
func (*BatchInsertResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{5}
}

func (x *BatchInsertResponse) GetInserted() int64 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *BatchInsertResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchInsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LookUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	FuncName      string                 `protobuf:"bytes,2,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	MinTime       int64                  `protobuf:"varint,3,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	MaxTime       int64                  `protobuf:"varint,4,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookUpRequest) Reset() {
	*x = LookUpRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookUpRequest) ProtoMessage() {}

func (x *LookUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookUpRequest.ProtoReflect.Descriptor instead.
func (*LookUpRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{6}
}

func (x *LookUpRequest) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LookUpRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *LookUpRequest) GetMinTime() int64 {
	if x != nil {
		return x.MinTime
	}
	return 0
}

func (x *LookUpRequest) GetMaxTime() int64 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

type LookUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanAnswer     bool                   `protobuf:"varint,1,opt,name=can_answer,json=canAnswer,proto3" json:"can_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookUpResponse) Reset() {
	*x = LookUpResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookUpResponse) ProtoMessage() {}

func (x *LookUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookUpResponse.ProtoReflect.Descriptor instead.
func (*LookUpResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{7}
}

func (x *LookUpResponse) GetCanAnswer() bool {
	if x != nil {
		return x.CanAnswer
	}
	return false
}

type EvalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncName      string                 `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Labels        []*Label               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	OtherArgs     float64                `protobuf:"fixed64,3,opt,name=other_args,json=otherArgs,proto3" json:"other_args,omitempty"`
	MinTime       int64                  `protobuf:"varint,4,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	MaxTime       int64                  `protobuf:"varint,5,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
	CurTime       int64                  `protobuf:"varint,6,opt,name=cur_time,json=curTime,proto3" json:"cur_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{8}
}

func (x *EvalRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *EvalRequest) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EvalRequest) GetOtherArgs() float64 {
	if x != nil {
		return x.OtherArgs
	}
	return 0
}

func (x *EvalRequest) GetMinTime() int64 {
	if x != nil {
		return x.MinTime
	}
	return 0
}

func (x *EvalRequest) GetMaxTime() int64 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

func (x *EvalRequest) GetCurTime() int64 {
	if x != nil {
		return x.CurTime
	}
	return 0
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{9}
}

func (x *Sample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*Sample              `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{10}
}

func (x *EvalResponse) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *EvalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{13}
}

type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalSeries     uint64                 `protobuf:"varint,2,opt,name=total_series,json=totalSeries,proto3" json:"total_series,omitempty"`
	SketchedSeries  uint64                 `protobuf:"varint,3,opt,name=sketched_series,json=sketchedSeries,proto3" json:"sketched_series,omitempty"`
	SamplesInserted uint64                 `protobuf:"varint,4,opt,name=samples_inserted,json=samplesInserted,proto3" json:"samples_inserted,omitempty"`
	PartitionStart  int32                  `protobuf:"varint,5,opt,name=partition_start,json=partitionStart,proto3" json:"partition_start,omitempty"`
	PartitionEnd    int32                  `protobuf:"varint,6,opt,name=partition_end,json=partitionEnd,proto3" json:"partition_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_psksketch_v1_psksketch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_psksketch_v1_psksketch_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatsResponse) GetTotalSeries() uint64 {
	if x != nil {
		return x.TotalSeries
	}
	return 0
}

func (x *StatsResponse) GetSketchedSeries() uint64 {
	if x != nil {
		return x.SketchedSeries
	}
	return 0
}

func (x *StatsResponse) GetSamplesInserted() uint64 {
	if x != nil {
		return x.SamplesInserted
	}
	return 0
}

func (x *StatsResponse) GetPartitionStart() int32 {
	if x != nil {
		return x.PartitionStart
	}
	return 0
}

func (x *StatsResponse) GetPartitionEnd() int32 {
	if x != nil {
		return x.PartitionEnd
	}
	return 0
}

var File_api_psksketch_v1_psksketch_proto protoreflect.FileDescriptor

const file_api_psksketch_v1_psksketch_proto_rawDesc = "" +
	"\n" +
	" api/psksketch/v1/psksketch.proto\x12\fpsksketch.v1\"1\n" +
	"\x05Label\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"p\n" +
	"\rInsertRequest\x12+\n" +
	"\x06labels\x18\x01 \x03(\v2\x13.psksketch.v1.LabelR\x06labels\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"@\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x12BatchInsertRequest\x129\n" +
	"\vtime_series\x18\x01 \x03(\v2\x18.psksketch.v1.TimeSeriesR\n" +
	"timeSeries\"i\n" +
	"\n" +
	"TimeSeries\x12+\n" +
	"\x06labels\x18\x01 \x03(\v2\x13.psksketch.v1.LabelR\x06labels\x12.\n" +
	"\asamples\x18\x02 \x03(\v2\x14.psksketch.v1.SampleR\asamples\"_\n" +
	"\x13BatchInsertResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x03R\binserted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x03R\x06failed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8f\x01\n" +
	"\rLookUpRequest\x12+\n" +
	"\x06labels\x18\x01 \x03(\v2\x13.psksketch.v1.LabelR\x06labels\x12\x1b\n" +
	"\tfunc_name\x18\x02 \x01(\tR\bfuncName\x12\x19\n" +
	"\bmin_time\x18\x03 \x01(\x03R\aminTime\x12\x19\n" +
	"\bmax_time\x18\x04 \x01(\x03R\amaxTime\"/\n" +
	"\x0eLookUpResponse\x12\x1d\n" +
	"\n" +
	"can_answer\x18\x01 \x01(\bR\tcanAnswer\"\xc7\x01\n" +
	"\vEvalRequest\x12\x1b\n" +
	"\tfunc_name\x18\x01 \x01(\tR\bfuncName\x12+\n" +
	"\x06labels\x18\x02 \x03(\v2\x13.psksketch.v1.LabelR\x06labels\x12\x1d\n" +
	"\n" +
	"other_args\x18\x03 \x01(\x01R\totherArgs\x12\x19\n" +
	"\bmin_time\x18\x04 \x01(\x03R\aminTime\x12\x19\n" +
	"\bmax_time\x18\x05 \x01(\x03R\amaxTime\x12\x19\n" +
	"\bcur_time\x18\x06 \x01(\x03R\acurTime\"<\n" +
	"\x06Sample\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"T\n" +
	"\fEvalResponse\x12.\n" +
	"\asamples\x18\x01 \x03(\v2\x14.psksketch.v1.SampleR\asamples\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\x84\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x0e\n" +
	"\fStatsRequest\"\xed\x01\n" +
	"\rStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\ftotal_series\x18\x02 \x01(\x04R\vtotalSeries\x12'\n" +
	"\x0fsketched_series\x18\x03 \x01(\x04R\x0esketchedSeries\x12)\n" +
	"\x10samples_inserted\x18\x04 \x01(\x04R\x0fsamplesInserted\x12'\n" +
	"\x0fpartition_start\x18\x05 \x01(\x05R\x0epartitionStart\x12#\n" +
	"\rpartition_end\x18\x06 \x01(\x05R\fpartitionEnd2\xb3\x03\n" +
	"\rSketchService\x12C\n" +
	"\x06Insert\x12\x1b.psksketch.v1.InsertRequest\x1a\x1c.psksketch.v1.InsertResponse\x12R\n" +
	"\vBatchInsert\x12 .psksketch.v1.BatchInsertRequest\x1a!.psksketch.v1.BatchInsertResponse\x12C\n" +
	"\x06LookUp\x12\x1b.psksketch.v1.LookUpRequest\x1a\x1c.psksketch.v1.LookUpResponse\x12=\n" +
	"\x04Eval\x12\x19.psksketch.v1.EvalRequest\x1a\x1a.psksketch.v1.EvalResponse\x12C\n" +
	"\x06Health\x12\x1b.psksketch.v1.HealthRequest\x1a\x1c.psksketch.v1.HealthResponse\x12@\n" +
	"\x05Stats\x12\x1a.psksketch.v1.StatsRequest\x1a\x1b.psksketch.v1.StatsResponseBFZDgithub.com/promsketch/promsketch-dropin/api/psksketch/v1;psksketchpbb\x06proto3"

var (
	file_api_psksketch_v1_psksketch_proto_rawDescOnce sync.Once
	file_api_psksketch_v1_psksketch_proto_rawDescData []byte
)

func file_api_psksketch_v1_psksketch_proto_rawDescGZIP() []byte {
	file_api_psksketch_v1_psksketch_proto_rawDescOnce.Do(func() {
		file_api_psksketch_v1_psksketch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_psksketch_v1_psksketch_proto_rawDesc), len(file_api_psksketch_v1_psksketch_proto_rawDesc)))
	})
	return file_api_psksketch_v1_psksketch_proto_rawDescData
}

var file_api_psksketch_v1_psksketch_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_psksketch_v1_psksketch_proto_goTypes = []any{
	(*Label)(nil),               // 0: psksketch.v1.Label
	(*InsertRequest)(nil),       // 1: psksketch.v1.InsertRequest
	(*InsertResponse)(nil),      // 2: psksketch.v1.InsertResponse
	(*BatchInsertRequest)(nil),  // 3: psksketch.v1.BatchInsertRequest
	(*TimeSeries)(nil),          // 4: psksketch.v1.TimeSeries
	(*BatchInsertResponse)(nil), // 5: psksketch.v1.BatchInsertResponse
	(*LookUpRequest)(nil),       // 6: psksketch.v1.LookUpRequest
	(*LookUpResponse)(nil),      // 7: psksketch.v1.LookUpResponse
	(*EvalRequest)(nil),         // 8: psksketch.v1.EvalRequest
	(*Sample)(nil),              // 9: psksketch.v1.Sample
	(*EvalResponse)(nil),        // 10: psksketch.v1.EvalResponse
	(*HealthRequest)(nil),       // 11: psksketch.v1.HealthRequest
	(*HealthResponse)(nil),      // 12: psksketch.v1.HealthResponse
	(*StatsRequest)(nil),        // 13: psksketch.v1.StatsRequest
	(*StatsResponse)(nil),       // 14: psksketch.v1.StatsResponse
}
var file_api_psksketch_v1_psksketch_proto_depIdxs = []int32{
	0,  // 0: psksketch.v1.InsertRequest.labels:type_name -> psksketch.v1.Label
	4,  // 1: psksketch.v1.BatchInsertRequest.time_series:type_name -> psksketch.v1.TimeSeries
	0,  // 2: psksketch.v1.TimeSeries.labels:type_name -> psksketch.v1.Label
	9,  // 3: psksketch.v1.TimeSeries.samples:type_name -> psksketch.v1.Sample
	0,  // 4: psksketch.v1.LookUpRequest.labels:type_name -> psksketch.v1.Label
	0,  // 5: psksketch.v1.EvalRequest.labels:type_name -> psksketch.v1.Label
	9,  // 6: psksketch.v1.EvalResponse.samples:type_name -> psksketch.v1.Sample
	1,  // 7: psksketch.v1.SketchService.Insert:input_type -> psksketch.v1.InsertRequest
	3,  // 8: psksketch.v1.SketchService.BatchInsert:input_type -> psksketch.v1.BatchInsertRequest
	6,  // 9: psksketch.v1.SketchService.LookUp:input_type -> psksketch.v1.LookUpRequest
	8,  // 10: psksketch.v1.SketchService.Eval:input_type -> psksketch.v1.EvalRequest
	11, // 11: psksketch.v1.SketchService.Health:input_type -> psksketch.v1.HealthRequest
	13, // 12: psksketch.v1.SketchService.Stats:input_type -> psksketch.v1.StatsRequest
	2,  // 13: psksketch.v1.SketchService.Insert:output_type -> psksketch.v1.InsertResponse
	5,  // 14: psksketch.v1.SketchService.BatchInsert:output_type -> psksketch.v1.BatchInsertResponse
	7,  // 15: psksketch.v1.SketchService.LookUp:output_type -> psksketch.v1.LookUpResponse
	10, // 16: psksketch.v1.SketchService.Eval:output_type -> psksketch.v1.EvalResponse
	12, // 17: psksketch.v1.SketchService.Health:output_type -> psksketch.v1.HealthResponse
	14, // 18: psksketch.v1.SketchService.Stats:output_type -> psksketch.v1.StatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_psksketch_v1_psksketch_proto_init() }
func file_api_psksketch_v1_psksketch_proto_init() {
	if File_api_psksketch_v1_psksketch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_psksketch_v1_psksketch_proto_rawDesc), len(file_api_psksketch_v1_psksketch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_psksketch_v1_psksketch_proto_goTypes,
		DependencyIndexes: file_api_psksketch_v1_psksketch_proto_depIdxs,
		MessageInfos:      file_api_psksketch_v1_psksketch_proto_msgTypes,
	}.Build()
	File_api_psksketch_v1_psksketch_proto = out.File
	file_api_psksketch_v1_psksketch_proto_goTypes = nil
	file_api_psksketch_v1_psksketch_proto_depIdxs = nil
}
