// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/psksketch/v1/psksketch.proto

package psksketchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SketchService_Insert_FullMethodName      = "/psksketch.v1.SketchService/Insert"
	SketchService_BatchInsert_FullMethodName = "/psksketch.v1.SketchService/BatchInsert"
	SketchService_LookUp_FullMethodName      = "/psksketch.v1.SketchService/LookUp"
	SketchService_Eval_FullMethodName        = "/psksketch.v1.SketchService/Eval"
	SketchService_Health_FullMethodName      = "/psksketch.v1.SketchService/Health"
	SketchService_Stats_FullMethodName       = "/psksketch.v1.SketchService/Stats"
)

// SketchServiceClient is the client API for SketchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SketchService provides distributed sketch operations
type SketchServiceClient interface {
	// Insert a sample into the sketch storage
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// BatchInsert inserts multiple samples in one RPC call
	BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*BatchInsertResponse, error)
	// LookUp checks if a query can be answered by sketches
	LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error)
	// Eval executes a sketch query and returns results
	Eval(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error)
	// Health returns the health status of this node
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Stats returns node statistics
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type sketchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSketchServiceClient(cc grpc.ClientConnInterface) SketchServiceClient {
	return &sketchServiceClient{cc}
}

func (c *sketchServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, SketchService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchServiceClient) BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*BatchInsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResponse)
	err := c.cc.Invoke(ctx, SketchService_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchServiceClient) LookUp(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LookUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookUpResponse)
	err := c.cc.Invoke(ctx, SketchService_LookUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchServiceClient) Eval(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvalResponse)
	err := c.cc.Invoke(ctx, SketchService_Eval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SketchService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SketchService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SketchServiceServer is the server API for SketchService service.
// All implementations must embed UnimplementedSketchServiceServer
// for forward compatibility.
//
// SketchService provides distributed sketch operations
type SketchServiceServer interface {
	// Insert a sample into the sketch storage
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// BatchInsert inserts multiple samples in one RPC call
	BatchInsert(context.Context, *BatchInsertRequest) (*BatchInsertResponse, error)
	// LookUp checks if a query can be answered by sketches
	LookUp(context.Context, *LookUpRequest) (*LookUpResponse, error)
	// Eval executes a sketch query and returns results
	Eval(context.Context, *EvalRequest) (*EvalResponse, error)
	// Health returns the health status of this node
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Stats returns node statistics
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedSketchServiceServer()
}

// UnimplementedSketchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSketchServiceServer struct{}

func (UnimplementedSketchServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedSketchServiceServer) BatchInsert(context.Context, *BatchInsertRequest) (*BatchInsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedSketchServiceServer) LookUp(context.Context, *LookUpRequest) (*LookUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookUp not implemented")
}
func (UnimplementedSketchServiceServer) Eval(context.Context, *EvalRequest) (*EvalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Eval not implemented")
}
func (UnimplementedSketchServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSketchServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedSketchServiceServer) mustEmbedUnimplementedSketchServiceServer() {}
func (UnimplementedSketchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSketchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SketchServiceServer will
// result in compilation errors.
type UnsafeSketchServiceServer interface {
	mustEmbedUnimplementedSketchServiceServer()
}

func RegisterSketchServiceServer(s grpc.ServiceRegistrar, srv SketchServiceServer) {
	// If the following call panics, it indicates UnimplementedSketchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SketchService_ServiceDesc, srv)
}

func _SketchService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchService_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).BatchInsert(ctx, req.(*BatchInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchService_LookUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).LookUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_LookUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).LookUp(ctx, req.(*LookUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchService_Eval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).Eval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_Eval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).Eval(ctx, req.(*EvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SketchService_ServiceDesc is the grpc.ServiceDesc for SketchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SketchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "psksketch.v1.SketchService",
	HandlerType: (*SketchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _SketchService_Insert_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _SketchService_BatchInsert_Handler,
		},
		{
			MethodName: "LookUp",
			Handler:    _SketchService_LookUp_Handler,
		},
		{
			MethodName: "Eval",
			Handler:    _SketchService_Eval_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SketchService_Health_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _SketchService_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/psksketch/v1/psksketch.proto",
}
