apiVersion: 1

datasources:
  - name: PromSketch-Dropin
    type: prometheus
    uid: promsketch-dashboard
    access: proxy
    url: http://pskquery:8480
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true

  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics-dashboard
    access: proxy
    url: http://victoriametrics:8428
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
