apiVersion: 1

datasources:
  - name: PromSketch-Dropin
    type: prometheus
    uid: promsketch-dashboard
    access: proxy
    url: http://localhost:9100
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true

  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics-dashboard
    access: proxy
    url: http://localhost:8428
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true

  - name: Prometheus
    type: prometheus
    uid: prometheus-dashboard
    access: proxy
    url: http://localhost:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
